version: "3.5"
services:
  postgres:
    container_name: postgres
    image: postgres:12.4
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    networks:
      - postgres
 
  pgadmin:
    links:
      - postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
    environment: 
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@mail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: