/* Grant all */
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA foo TO mygrp;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA foo TO mygrp;

/* Default Grant */
ALTER DEFAULT PRIVILEGES IN SCHEMA foo GRANT ALL PRIVILEGES ON TABLES TO mygrp;
ALTER DEFAULT PRIVILEGES IN SCHEMA foo GRANT USAGE          ON SEQUENCES TO mygrp;



